version: "3.8"

services:
  db-test:
    image: postgres:15-alpine
    container_name: my_postgres_test_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - test-network

  server-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_express_test
    command: sh -c "npx prisma db push && npx vitest run"
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://test:test@db-test:5432/test_db
    depends_on:
      - db-test
    volumes:
      - ./test-results:/usr/src/server/test-results
    networks:
      - test-network

networks:
  test-network:
    driver: bridge